name: zixine Kernel Build (MamboSu + SUSFS)

on:
  workflow_dispatch:
    inputs:
      kernel_name:
        description: 'Custom Kernel Name (Leave empty for default)'
        required: false
        default: ''
        type: string
      release_status:
        description: 'Release Status'
        required: true
        type: choice
        default: 'RELEASE'
        options:
          - 'RELEASE'
          - 'BETA'
      clang_version:
        description: 'Select Clang Version'
        required: true
        type: choice
        options:
          - 'r536225 (Clang 19)'
          - 'r547379 (Clang 20)'
          - 'r589343 (Clang 21)' # <--- Opsi Baru
      performance_patch:
        description: 'Select Device SoC for Performance Tuning'
        required: true
        type: choice
        default: 'Universal'
        options:
          - 'Snapdragon'
          - 'MediaTek'
          - 'Universal'

permissions:
  contents: write

jobs:
  build:
    name: Build Kernel GKI
    runs-on: ubuntu-22.04

    steps:
      - name: Free disk space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 8192
          swap-size-mb: 10240
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-codeql: 'true'

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Install build tools
        run: |
          sudo apt update && sudo apt upgrade -y
          sudo apt install -y git curl repo build-essential bc bison flex libssl-dev \
            libelf-dev python3 python3-pip unzip zip rsync libncurses-dev lld

      - name: Init & Sync GKI Source
        run: |
          mkdir gki && cd gki
          repo init -u https://android.googlesource.com/kernel/manifest -b common-android12-5.10 --depth=1
          repo sync -c --no-tags --no-clone-bundle --optimized-fetch -j$(nproc --all)

      - name: Update kernel source for GKI 5.10 (Rama)
        run: |
          cd gki/common
          echo "Switching source to Rama..."
          git remote add rama https://github.com/ramabondanp/android_kernel_common-5.10.git
          git fetch -j12 rama
          git checkout -b update-android12-5.10-staging rama/android12-5.10-staging
          
          # Membersihkan KernelSU lama jika ada, agar MamboSu bisa masuk
          if [ -d "drivers/staging/kernelsu" ]; then
            echo "ðŸ—‘ï¸ Removing existing KernelSU folder..."
            rm -rf drivers/staging/kernelsu
          fi

      - name: Apply Snapdragon Performance Patch
        if: github.event.inputs.performance_patch == 'Snapdragon'
        working-directory: gki/common
        run: |
          echo "[Snapdragon] Applying qcom-cpufreq-hw performance patch"
          TARGET="drivers/cpufreq/qcom-cpufreq-hw.c"
          SRC_URL="https://raw.githubusercontent.com/Pzqqt/android_kernel_xiaomi_marble/refs/heads/melt-rebase/drivers/cpufreq/qcom-cpufreq-hw.c"
          if [ ! -f "$TARGET" ]; then
            echo "Target file not found: $TARGET"
            exit 1
          fi
          curl -L "$SRC_URL" -o /tmp/qcom-cpufreq-hw.c
          grep -q "qcom_cpufreq_hw" /tmp/qcom-cpufreq-hw.c || exit 1
          cp /tmp/qcom-cpufreq-hw.c "$TARGET"
          echo "[Snapdragon] Patch applied."

      - name: Tweak build config
        run: |
          sed -i '2d' gki/common/build.config.gki

      - name: Setup MamboSu & SUSFS
        run: |
          cd gki/common
          echo "[6/12] Setup MamboSu & SUSFS"
          curl -LSs "https://raw.githubusercontent.com/MamboSu/MamboSu/main/kernel/setup.sh" | bash -s main
          
          git clone https://gitlab.com/simonpunk/susfs4ksu/ -b gki-android12-5.10 sus
          rm -rf sus/.git
          susfs=sus/kernel_patches
          cp -r $susfs/fs .
          cp -r $susfs/include .
          cp -r $susfs/50_add_susfs_in_gki-android12-5.10.patch .
          patch -p1 < 50_add_susfs_in_gki-android12-5.10.patch
          echo "[âœ“] MamboSu & SUSFS patched"

      - name: Fix Stack Protector
        working-directory: gki/common
        run: |
          echo " Applying manual Stack Protector fix"
          sed -i '/config STACKPROTECTOR_PER_TASK/{n;s/def_bool y/bool "Stack Protector per task"\n\tdefault y/;}' arch/arm64/Kconfig
          echo "# CONFIG_STACKPROTECTOR_PER_TASK is not set" >> arch/arm64/configs/gki_defconfig
          echo " Stack Protector fix applied manually."

      - name: Patch module & DRM (Xiaomi Compat)
        working-directory: gki/common
        run: |
          echo " Applying compatibility patch for Xiaomi devices"
          sed -i '/pr_warn.*disagrees about version of symbol.*/,+1 s/.*/return 1;/' kernel/module.c
          sed -i '/^static int drm_atomic_check_valid_clones/,/^}/d' drivers/gpu/drm/drm_atomic_helper.c
          sed -i '/ret = drm_atomic_check_valid_clones/,/return ret;/d' drivers/gpu/drm/drm_atomic_helper.c
          echo " Perbaikan selesai"

      - name: Remove check_defconfig
        run: |
          echo " [Clean-up] Deleting check_defconfig to prevent build error"
          sed -i 's/check_defconfig//' gki/common/build.config.gki

      - name: Inject All Kernel Configs
        working-directory: gki/common
        run: |
          echo "Adding complete kernel configuration"
          DEFCONFIG="arch/arm64/configs/gki_defconfig"
          PERFORMANCE_PATCH="${{ github.event.inputs.performance_patch }}"
          
          # 1. Config MamboSu (Base KSU) & SUSFS
          cat >> $DEFCONFIG <<EOF
          CONFIG_KSU=y
          CONFIG_KPM=n
          CONFIG_KSU_SUSFS_SUS_SU=n
          CONFIG_KSU_SYSCALL_HOOK=n
          CONFIG_KSU_SUSFS=y
          CONFIG_KSU_SUSFS_HAS_MAGIC_MOUNT=y
          CONFIG_KSU_SUSFS_SUS_PATH=y
          CONFIG_KSU_SUSFS_SUS_MOUNT=y
          CONFIG_KSU_SUSFS_SUS_KSTAT_SPOOF_GENERIC=y
          CONFIG_KSU_SUSFS_SUS_KSTAT=y
          CONFIG_KSU_SUSFS_AUTO_ADD_SUS_KSU_DEFAULT_MOUNT=y
          CONFIG_KSU_SUSFS_AUTO_ADD_SUS_BIND_MOUNT=y
          CONFIG_KSU_SUSFS_AUTO_ADD_SUS_KSTAT=y
          CONFIG_KSU_SUSFS_SUS_OVERLAYFS=n
          CONFIG_KSU_SUSFS_TRY_UMOUNT=y
          CONFIG_KSU_SUSFS_AUTO_ADD_TRY_UMOUNT_FOR_BIND_MOUNT=y
          CONFIG_KSU_SUSFS_SPOOF_UNAME=y
          CONFIG_KSU_SUSFS_ENABLE_LOG=y
          CONFIG_KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS=y
          CONFIG_KSU_SUSFS_SPOOF_CMDLINE_OR_BOOTCONFIG=y
          CONFIG_KSU_SUSFS_OPEN_REDIRECT=y
          CONFIG_KSU_MANUAL_HOOK=n
          CONFIG_KSU_HAS_MANUAL_HOOK=n
          CONFIG_KPROBES=y
          CONFIG_HAVE_KPROBES=y
          CONFIG_KRETPROBES=y
          CONFIG_KPROBE_EVENTS=y
          EOF

          # 2. Config Performa
          if [ "$PERFORMANCE_PATCH" = "MediaTek" ]; then
             echo "CONFIG_HZ=500" >> $DEFCONFIG
          elif [ "$PERFORMANCE_PATCH" = "Universal" ]; then
             echo "CONFIG_HZ_300=y" >> $DEFCONFIG
             echo "CONFIG_CPU_FREQ=y" >> $DEFCONFIG
             echo "CONFIG_HIGH_RES_TIMERS=y" >> $DEFCONFIG
          fi

          # 3. Optimasi Network & I/O
          cat >> $DEFCONFIG <<EOF
          CONFIG_TMPFS_XATTR=y
          CONFIG_TMPFS_POSIX_ACL=y
          CONFIG_IP_NF_TARGET_TTL=y
          CONFIG_IP6_NF_TARGET_HL=y
          CONFIG_IP6_NF_MATCH_HL=y
          CONFIG_TCP_CONG_ADVANCED=y
          CONFIG_TCP_CONG_BBR=y
          CONFIG_NET_SCH_FQ=y
          CONFIG_TCP_CONG_BIC=n
          CONFIG_TCP_CONG_WESTWOOD=n
          CONFIG_TCP_CONG_HTCP=n
          CONFIG_DEFAULT_BBR=y
          CONFIG_CPU_FREQ_DEFAULT_GOV_SCHEDUTIL=y
          CONFIG_SCHED_TUNE=y
          CONFIG_MQ_IOSCHED_KYBER=y
          CONFIG_MQ_IOSCHED_BFQ=y
          CONFIG_IOSCHED_BFQ=y
          CONFIG_BFQ_GROUP_IOSCHED=y
          EOF

      - name: Set version
        working-directory: gki/common
        run: |
          echo "" > scripts/setlocalversion
          chmod +x scripts/setlocalversion
          KERNEL_NAME_INPUT="${{ github.event.inputs.kernel_name }}"
          PERFORMANCE_PATCH="${{ github.event.inputs.performance_patch }}"

          SUFFIX=""
          if [ -n "$KERNEL_NAME_INPUT" ]; then
            SUFFIX="-$KERNEL_NAME_INPUT"
          fi
          SUFFIX="$SUFFIX"

          if [ "$PERFORMANCE_PATCH" = "Snapdragon" ]; then
            SUFFIX="$SUFFIX-Qcom"
          elif [ "$PERFORMANCE_PATCH" = "MediaTek" ]; then
            SUFFIX="$SUFFIX-Mtk"
          elif [ "$PERFORMANCE_PATCH" = "Universal" ]; then
            SUFFIX="$SUFFIX-Uni"
          fi
          
          echo "Setting custom kernel name: $SUFFIX"
          if grep -q '^EXTRAVERSION *=' Makefile; then
            sed -i "s/^EXTRAVERSION *=.*/EXTRAVERSION = $SUFFIX/" Makefile
          else
            echo "EXTRAVERSION = $SUFFIX" >> Makefile
          fi

      - name: Setup Clang
        working-directory: gki
        run: |
          mkdir -p prebuilts-master/clang/host/linux-x86
          if [ "${{ github.event.inputs.clang_version }}" == "r536225 (Clang 19)" ]; then
            CLANG_VER="clang-r536225"
            CLANG_URL="https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/main-kernel-2025/clang-r536225.tar.gz"
          elif [ "${{ github.event.inputs.clang_version }}" == "r547379 (Clang 20)" ]; then
            CLANG_VER="clang-r547379"
            CLANG_URL="https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/62cdcefa89e31af2d72c366e8b5ef8db84caea62/clang-r547379.tar.gz"
          else
            # Konfigurasi untuk Clang 21
            CLANG_VER="clang-r589343"
            CLANG_URL="https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/main/clang-r589343.tar.gz"
          fi
          
          echo "CLANG_VER=$CLANG_VER" >> $GITHUB_ENV
          mkdir -p prebuilts-master/clang/host/linux-x86/$CLANG_VER
          cd prebuilts-master/clang/host/linux-x86
          
          echo "Downloading Clang from: $CLANG_URL"
          curl -L "${CLANG_URL}" | tar -xz -C $CLANG_VER
          
          rm -rf clang-r416183b
          ln -sf $CLANG_VER clang-r416183b

      - name: Commit changes
        working-directory: gki/common
        run: |
          git add .
          git commit -m "Final clean tree before build" || true

      - name: Compile
        working-directory: gki
        run: |
          LTO=thin BUILD_CONFIG=common/build.config.gki.aarch64 build/build.sh

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Image-MamboSu-${{ github.event.inputs.performance_patch }}
          path: gki/out/android12-5.10/dist/Image
